### ISSUE TITLE
Adding `next-superjson-plugin` creating Error

### ISSUE THREAD

**Issue by Ashutsoh1729** [AntonioErdeljac/next13-messenger#23]
Here I added the next-superjson-plugin to the project 

And after that It started showing error 

I have changed different versions of `next` and `next-superjson-plugin` but still it don't works

Here are the codes from different parts 

from `next.config.js`
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
    experimental: {
        appDir: true,
        swcPlugins: [["next-superjson-plugin", {}]]
    },
}

module.exports = nextConfig
```
and the `package.json` for the version check

```json
   "next": "13.3.1",
    "next-auth": "^4.22.1",
    "next-superjson-plugin": "^0.5.8",
    "postcss": "8.4.24",
```

And here is the error that is coming out 

error - ./node_modules/next/dist/client/dev/amp-dev.js
Error: failed to process failed to invoke plugin: failed to invoke plugin on 'Some("/Users/ashutoshhota/Coding/web development/Next JS/Ongoing Projects/Messenger Clone/Messenger Clone/Messenger-Clone/node_modules/next/dist/client/dev/amp-dev.js")'

Caused by:
    0: failed to invoke `/Users/ashutoshhota/Coding/web development/Next JS/Ongoing Projects/Messenger Clone/Messenger Clone/Messenger-Clone/node_modules/next-superjson-plugin/dist/next_superjson.wasm` as js transform plugin at /Users/ashutoshhota/Coding/web development/Next JS/Ongoing Projects/Messenger Clone/Messenger Clone/Messenger-Clone/node_modules/next-superjson-plugin/dist/next_superjson.wasm
    1: RuntimeError: unreachable
    2: unreachable
    
Please Help

**Comment by Ashutsoh1729** [comment]
I have solved the issue. I changed the next.js versions to the v-13.4.5 and the next-superjson-plugin to ^0.5.8 and it shows no error

**Comment by hmongdev** [comment]
> I have solved the issue. I changed the next.js versions to the v-13.4.5 and the next-superjson-plugin to ^0.5.8 and it shows no error

I was having this issue yesterday, thank you for the tip!

I'm on NextJS 14. appDir is no longer required.

Just downgrade `next-superjson-plugin` to ^0.5.8 and it worked for me.

Thank you,
