### ISSUE TITLE
Type 'UseFormRegisterReturn<string>' is not assignable to type 'ReactNode'.

### ISSUE THREAD

**Issue by Nicitaa** [AntonioErdeljac/next13-messenger#3]
![image](https://user-images.githubusercontent.com/39565703/236668449-428472cd-889a-408c-9bc2-2b4da22d1701.png)
https://youtu.be/PGPGcKBpAk8?list=PLMBfii-0liG_uCliODb_aUIuSley8awL_&t=2071

**Comment by AntonioErdeljac** [comment]
You need to use the <input> element, not <div> element :)

**Comment by Nicitaa** [comment]
Yes thank you
